// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0_N7sHHMSLOM9hnwswHphJ8FKWfnrafg',
    appId: '1:203198940064:web:ee23b400404250a4785ac5',
    messagingSenderId: '203198940064',
    projectId: 'trekmate-5985f',
    authDomain: 'trekmate-5985f.firebaseapp.com',
    storageBucket: 'trekmate-5985f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvrbzxv0QIXmcNw0RZiQfVpgvtHy3oRZA',
    appId: '1:203198940064:android:da0018d117a2092a785ac5',
    messagingSenderId: '203198940064',
    projectId: 'trekmate-5985f',
    storageBucket: 'trekmate-5985f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsXtTT-fp7Ybi0oLJYd5LLBRXYAulvsvo',
    appId: '1:203198940064:ios:05ca2d7c0dbe8419785ac5',
    messagingSenderId: '203198940064',
    projectId: 'trekmate-5985f',
    storageBucket: 'trekmate-5985f.appspot.com',
    iosBundleId: 'com.example.trekmateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsXtTT-fp7Ybi0oLJYd5LLBRXYAulvsvo',
    appId: '1:203198940064:ios:05ca2d7c0dbe8419785ac5',
    messagingSenderId: '203198940064',
    projectId: 'trekmate-5985f',
    storageBucket: 'trekmate-5985f.appspot.com',
    iosBundleId: 'com.example.trekmateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0_N7sHHMSLOM9hnwswHphJ8FKWfnrafg',
    appId: '1:203198940064:web:e8e658b41284dec2785ac5',
    messagingSenderId: '203198940064',
    projectId: 'trekmate-5985f',
    authDomain: 'trekmate-5985f.firebaseapp.com',
    storageBucket: 'trekmate-5985f.appspot.com',
  );
}
